services:
  frontend:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data

    env_file:
      - app/.env
    command: streamlit run main.py
    networks:
      - app-network

networks:
  app-network:
